name 中青看点2

on
  workflow_dispatch
  schedule
    - cron '0 13-231   '
jobs
  build
    runs-on ubuntu-latest 
    if github.event.repository.owner.id == github.event.sender.id
    env
        User ${{ github.event.repository.owner.id }}
    steps

      - name Checkout
        run 
          git clone httpsgithub.comcaixukun112js.git ~js
      - name Use Node.js 14.x
        uses actionssetup-node@v1
        with
          node-version 14.x
      - name npm install
        run 
          cd ~js
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name '运行 【中青看点2】'
        run 
          cd ~js   
          node Task/youthSign2.js